export const INCORRECT_DATA_ERROR_CODE = 400
export const UNAUTHORIZED_ERROR_CODE = 401
export const FORBIDDEN_ERROR_CODE = 403
export const NOT_FOUND_ERROR_CODE = 404
export const INTERSECTION_ERROR_CODE = 409
export const DEFAULT_ERROR_CODE = 500
export const DEFAULT_MESSAGE = "На сервере произошла ошибка."
export const NOT_FOUND_USER_ERROR = "Пользователь не найден."
export const NOT_FOUND_CARD_ERROR = "Карточка не найдена."
export const WRONG_AUTH_ERROR = 'Неверные имя пользоваеля или пароль.'
export const INTERSECTION_ERROR = 'Такой email уже существует.'
export const DELETE_CARD_FORBIDDEN_ERROR = 'Невозожно удалить чужую карточку.'
export const UNAUTHORIZED_ERROR = 'Необходимо авторизоваться.'
